services:
  - type: web
    name: qr-barcode-api
    runtime: node
    buildCommand: |
      npm install -g pm2
      npm install
      npm run build
    startCommand: pm2-runtime start ecosystem.config.js --env production
    env: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    plan: free